name: test
on:
  push:
    branches:
    - '*'
  pull_request:
    paths:
      - '**.go'
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # ratchet:actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # ratchet:actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true
      - name: Install upx
        run: sudo apt install -y upx
      - name: Test with go cli
        run: go test -v ./...